# Generated by Django 5.1.1 on 2024-10-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_rename_tag_webarchive_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webarchive',
            old_name='catagory',
            new_name='category',
        ),
    ]
