# Generated by Django 5.1.1 on 2024-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_rename_catagory_webarchive_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='webarchive',
            name='detail',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
    ]
